import React from "react";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Navbar from "../components/Navbar/navbar";
import Footer from "../components/Footer/footer";
import { CartContextProvider } from "../hooks/useCart";
import NextAuthProvider from "../providers/NextAuthProvider";
import { Toaster } from "react-hot-toast";
import { AuthModalContextProvider } from "../hooks/useAuthModal";
import AuthModal from "../components/Auth/AuthModal";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Bodat Chic Second",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=2"],
    apple: ["/apple-touch-icon.png?v=2"],
    shortcut: ["/apple-touch-icon.png"],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element | undefined {
  return (
    <html lang="en">
      <body className={`text-slate-700 ${poppins.className}`}>
        <Toaster
          toastOptions={{
            style: {
              background: "rgb(51 65 85)",
              color: "#fff",
            },
          }}
        />
        <NextAuthProvider>
          <CartContextProvider>
            <AuthModalContextProvider>
              <AuthModal />
              <div className="flex flex-col min-h-screen ">
                <Navbar />
                <main className="flex-grow bg-white font">{children}</main>
                <Footer />
              </div>
            </AuthModalContextProvider>
          </CartContextProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
